apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-dogs-api
  labels:
    app: cats-dogs-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cats-dogs-api
  template:
    metadata:
      labels:
        app: cats-dogs-api
    spec:
      containers:
        - name: cats-dogs-api
          image: ghcr.io/madihafathima/bits_mlops_assignment_2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            failureThreshold: 30 # up to 150s to finish starting (torch import + model load)
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
